from freeact.model.litellm.api import (
    DEFAULT_CODE_TAG_SYSTEM_TEMPLATE,
    DEFAULT_EXECUTION_ERROR_TEMPLATE,
    DEFAULT_EXECUTION_OUTPUT_TEMPLATE,
    DEFAULT_TOOL_USE_SYSTEM_TEMPLATE,
    LiteCodeActModel,
)
