import freeact.model.litellm.code_tag.model as ct
import freeact.model.litellm.tool_use.model as tu
from freeact.model.base import CodeActModel, CodeActModelTurn
from freeact.model.litellm.base.model import provider_name
from freeact.model.litellm.base.prompt import (
    EXECUTION_ERROR_TEMPLATE as DEFAULT_EXECUTION_ERROR_TEMPLATE,
)
from freeact.model.litellm.base.prompt import (
    EXECUTION_OUTPUT_TEMPLATE as DEFAULT_EXECUTION_OUTPUT_TEMPLATE,
)
from freeact.model.litellm.code_tag.prompt import SYSTEM_TEMPLATE as DEFAULT_CODE_TAG_SYSTEM_TEMPLATE
from freeact.model.litellm.tool_use.prompt import SYSTEM_TEMPLATE as DEFAULT_TOOL_USE_SYSTEM_TEMPLATE


class LiteCodeActModel(CodeActModel):
    """A [LiteLLM](https://github.com/BerriAI/litellm)-based code action model.

    Code actions are generated differently depending on the `tool_use` argument:

    - `tool_use=False`: Code actions are included directly into the model's response text,
      enclosed in `<code-action> ... </code-action>` tags. This instruction, among others, is given by the
      [`DEFAULT_CODE_TAG_SYSTEM_TEMPLATE`][freeact.model.litellm.api.DEFAULT_CODE_TAG_SYSTEM_TEMPLATE].

    - `tool_use=True`: Code actions are generated by calling an internal `execute_ipython_cell`
      tool. This instruction, among others, is given by the
      [`DEFAULT_TOOL_USE_SYSTEM_TEMPLATE`][freeact.model.litellm.api.DEFAULT_TOOL_USE_SYSTEM_TEMPLATE]

    - `tool_use=None`: A sensible default is chosen based on the model provider and name. Currently,
      a tool use approach is used for Anthropic and OpenAI models, a code tag approach is used for
      all other models.

    A custom system template can be provided with the `system_template` constructor argument.
    Its semantics should then match the `tool_use` argument value.

    Models whose `tool_use` property is `True` are also able to create and edit files. This allows
    them to store and edit code actions on disk (= long-term memory). Stored code actions can be
    loaded as *custom skills* via [`get_sources`][freeact.environment.CodeProvider.get_sources].

    Args:
        model_name: A model name supported by [LiteLLM](https://github.com/BerriAI/litellm).
        skill_sources: Source code of Python modules offered to the model as skills. They
            are utilized by generated code actions, if useful for the task. Skill sources are
            usually loaded and formatted with [`get_sources`][freeact.environment.CodeProvider.get_sources].
        system_template: A system template that guides the model to generate code actions.
            Must define a `{python_modules}` placeholder for `skill_sources`.
        execution_output_template: A prompt template for formatting successful code execution
            output. Must define an `{execution_feedback}` placeholder.
        execution_error_template: A prompt template for formatting code execution errors.
            Must define an `{execution_feedback}` placeholder.
        tool_use: Whether to generate code actions as tool calls. If `None`, a sensible
            default is chosen based on `model_name`.
        **kwargs: Default [chat completion](https://docs.litellm.ai/docs/completion) `kwargs`
            for [`request`][freeact.model.litellm.api.LiteCodeActModel.request] and
            [`feedback`][freeact.model.litellm.api.LiteCodeActModel.feedback] calls.
            These are merged with `request` and `feedback` specific completion `kwargs`
            where the latter have higher precedence in case of conflicting keys. The following
            `kwargs` are set internally and must not be set here: `stream`, `stream_options`,
            `messages`, and `tools`.
    """

    def __init__(
        self,
        model_name: str,
        skill_sources: str | None = None,
        system_template: str | None = None,
        execution_output_template: str | None = None,
        execution_error_template: str | None = None,
        tool_use: bool | None = None,
        **kwargs,
    ):
        self._tool_use = self._tool_use_enabled(model_name) if tool_use is None else tool_use

        if system_template is None:
            system_template = DEFAULT_TOOL_USE_SYSTEM_TEMPLATE if self.tool_use else DEFAULT_CODE_TAG_SYSTEM_TEMPLATE

        if execution_output_template is None:
            execution_output_template = DEFAULT_EXECUTION_OUTPUT_TEMPLATE

        if execution_error_template is None:
            execution_error_template = DEFAULT_EXECUTION_ERROR_TEMPLATE

        model_class = tu.LiteLLM if self.tool_use else ct.LiteLLM

        self.model = model_class(
            model_name=model_name,
            system_instruction=system_template.format(python_modules=skill_sources or ""),
            execution_output_template=execution_output_template,
            execution_error_template=execution_error_template,
            **kwargs,
        )

    @property
    def tool_use(self) -> bool:
        """Whether tool usage for code action generation and editing is enabled for this model."""
        return self._tool_use

    def request(
        self,
        user_query: str,
        **kwargs,
    ) -> CodeActModelTurn:
        """Initiates an interaction with this model from a user query.

        Args:
            user_query: The user query (a question, instruction, etc.)
            **kwargs: [Chat completion](https://docs.litellm.ai/docs/completion) arguments.
                These are merged with the model's default completion `kwargs`. Default
                completion `kwargs` have lower precedence in case of conflicting keys.

        Returns:
            CodeActModelTurn: An object for retrieving the model's response.
        """
        return self.model.request(user_query, **kwargs)

    def feedback(
        self,
        feedback: str,
        is_error: bool,
        tool_use_id: str | None,
        tool_use_name: str | None,
        **kwargs,
    ) -> CodeActModelTurn:
        """Initiates an interaction with this model from code execution feedback,
        allowing the model to refine or correct previous responses, or returning
        a final response to the user. A `feedback` call must follow a previous
        `request` or `feedback` call.

        Args:
            feedback: The feedback text from code execution.
            is_error: Whether the `feedback` text contains error information.
            **kwargs: [Chat completion](https://docs.litellm.ai/docs/completion) arguments.
                These are merged with the model's default completion `kwargs`. Default
                completion `kwargs` have lower precedence in case of conflicting keys.

        Returns:
            CodeActModelTurn: An object for retrieving the model's response.
        """
        return self.model.feedback(feedback, is_error, tool_use_id, tool_use_name, **kwargs)

    @staticmethod
    def _tool_use_enabled(model_name: str) -> bool:
        return provider_name(model_name) in ["anthropic", "openai"]
