name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v4
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ vars.CI_POETRY_VERSION }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          poetry env info
          poetry install
          pip list

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          poetry run pytest tests/unit

      - name: Run integration tests
        shell: bash -l {0}
        run: |
          docker pull ghcr.io/gradion-ai/ipybox:basic
          poetry run pytest tests/integration
